return{{rainfall=0.4,temperature=0.8,name="Beach",biomeTypes={"beach"}},
{rainfall=1.0,temperature=0.9,name="MushroomIslandShore",biomeTypes={"mushroom","beach"}},
{rainfall=0.3,temperature=0.2,name="Stone Beach",biomeTypes={"beach"}},
{rainfall=0.3,temperature=0.05,name="Cold Beach",biomeTypes={"cold","snowy","beach"}},
{rainfall=1.0,temperature=1.2,name="Tropics",biomeTypes={"wet","jungle","lush","ocean","river","beach","ScummyBee"}},
{rainfall=0.1,temperature=0.0,name="Ice Ocean",biomeTypes={"cold","ocean","snowy","beach"}},
{rainfall=0.4,temperature=0.5,name="Cold Ocean",biomeTypes={"cold","coniferous","ocean","forest","beach"}},
{rainfall=0.6,temperature=0.8,name="Temperate Ocean",biomeTypes={"cold","ocean","forest","beach"}},
{rainfall=0.2,temperature=0.8,name="Hot Ocean",biomeTypes={"hot","dry","ocean","sandy","beach","ScummyBee"}},
{rainfall=0.9,temperature=0.9,name="Wet Ocean",biomeTypes={"hot","wet","jungle","ocean","beach","ScummyBee"}},
{rainfall=0.9,temperature=0.9,name="Ocean Oasis",biomeTypes={"hot","wet","jungle","ocean","beach","ScummyBee"}},
{rainfall=0.8,temperature=0.7,name="Forest",biomeTypes={"forest"}},
{rainfall=0.8,temperature=0.25,name="Taiga",biomeTypes={"cold","coniferous","forest"}},
{rainfall=0.8,temperature=0.25,name="TaigaHills",biomeTypes={"cold","coniferous","forest","hills"}},
{rainfall=0.8,temperature=0.7,name="ForestHills",biomeTypes={"forest","hills"}},
{rainfall=0.8,temperature=0.95,name="JungleEdge",biomeTypes={"hot","wet","jungle","forest"}},
{rainfall=0.6,temperature=0.6,name="Birch Forest",biomeTypes={"forest"}},
{rainfall=0.6,temperature=0.6,name="Birch Forest Hills",biomeTypes={"forest","hills"}},
{rainfall=0.8,temperature=0.7,name="Roofed Forest",biomeTypes={"dense","spooky","forest"}},
{rainfall=0.4,temperature=-0.5,name="Cold Taiga",biomeTypes={"cold","coniferous","forest","snowy"}},
{rainfall=0.4,temperature=-0.5,name="Cold Taiga Hills",biomeTypes={"cold","coniferous","forest","hills","snowy"}},
{rainfall=0.8,temperature=0.3,name="Mega Taiga",biomeTypes={"cold","coniferous","forest"}},
{rainfall=0.8,temperature=0.3,name="Mega Taiga Hills",biomeTypes={"cold","coniferous","forest","hills"}},
{rainfall=0.3,temperature=0.2,name="Extreme Hills+",biomeTypes={"sparse","forest","mountain"}},
{rainfall=0.6,temperature=0.7,name="Magical Forest",biomeTypes={"magical","forest"}},
{rainfall=0.5,temperature=0.0,name="Alps Forest",biomeTypes={"cold","forest","mountain","snowy"}},
{rainfall=0.9,temperature=1.2,name="Bamboo Forest",biomeTypes={"dense","jungle","lush","forest"}},
{rainfall=0.9,temperature=0.5,name="Bog",biomeTypes={"wet","dead","forest","swamp"}},
{rainfall=0.6,temperature=0.5,name="Boreal Forest",biomeTypes={"dense","coniferous","lush","forest"}},
{rainfall=0.8,temperature=0.6,name="Cherry Blossom Grove",biomeTypes={"lush","magical","forest"}},
{rainfall=0.5,temperature=0.5,name="Coniferous Forest",biomeTypes={"dense","coniferous","forest","hills"}},
{rainfall=0.5,temperature=0.0,name="Snowy Coniferous Forest",biomeTypes={"cold","dense","coniferous","forest","hills","snowy"}},
{rainfall=0.3,temperature=0.4,name="Dead Forest",biomeTypes={"sparse","spooky","dead","forest"}},
{rainfall=0.8,temperature=0.6,name="Deciduous Forest",biomeTypes={"dense","dry","forest"}},
{rainfall=0.4,temperature=0.4,name="Fen",biomeTypes={"wet","dead","forest","swamp"}},
{rainfall=0.5,temperature=0.0,name="Frost Forest",biomeTypes={"cold","sparse","forest","snowy"}},
{rainfall=1.0,temperature=0.9,name="Fungi Forest",biomeTypes={"wet","lush","mushroom","magical","forest","swamp"}},
{rainfall=0.8,temperature=0.7,name="Grove",biomeTypes={"dense","lush","forest","plains"}},
{rainfall=0.9,temperature=0.8,name="Jade Cliffs",biomeTypes={"dense","forest","mountain"}},
{rainfall=0.9,temperature=0.8,name="Mangrove",biomeTypes={"wet","lush","ocean","river","forest","ScummyBee"}},
{rainfall=0.8,temperature=0.2,name="Maple Woods",biomeTypes={"cold","forest"}},
{rainfall=0.7,temperature=0.7,name="Meadow",biomeTypes={"lush","forest","plains"}},
{rainfall=0.7,temperature=0.7,name="Meadow Forest",biomeTypes={"lush","forest","plains"}},
{rainfall=0.1,temperature=0.5,name="Mountain",biomeTypes={"dry","forest","mountain"}},
{rainfall=1.0,temperature=0.7,name="Mystic Grove",biomeTypes={"wet","lush","magical","forest"}},
{rainfall=0.9,temperature=0.5,name="Kelp Forest",biomeTypes={"ocean","river","forest"}},
{rainfall=0.9,temperature=0.5,name="Ominous Woods",biomeTypes={"spooky","dead","magical","forest","swamp"}},
{rainfall=0.7,temperature=0.7,name="Orchard",biomeTypes={"sparse","lush","forest","plains"}},
{rainfall=1.0,temperature=1.0,name="Rainforest",biomeTypes={"dense","wet","jungle","lush","forest","hills"}},
{rainfall=0.7,temperature=0.7,name="Redwood Forest",biomeTypes={"dense","coniferous","forest"}},
{rainfall=0.5,temperature=0.5,name="Sacred Springs",biomeTypes={"dense","wet","lush","magical","forest","mountain"}},
{rainfall=0.8,temperature=0.5,name="Seasonal Forest",biomeTypes={"dense","lush","forest"}},
{rainfall=0.8,temperature=0.5,name="Shield",biomeTypes={"wet","coniferous","ocean","river","forest","ScummyBee"}},
{rainfall=0.9,temperature=0.5,name="Silkglades",biomeTypes={"spooky","dead","forest","swamp"}},
{rainfall=0.9,temperature=0.8,name="Sludgepit",biomeTypes={"wet","spooky","dead","forest","swamp","wasteland"}},
{rainfall=0.8,temperature=0.7,name="Spruce Woods",biomeTypes={"dense","coniferous","lush","forest"}},
{rainfall=1.2,temperature=0.8,name="Temperate Rainforest",biomeTypes={"wet","coniferous","lush","forest","hills"}},
{rainfall=0.2,temperature=0.6,name="Thicket",biomeTypes={"dense","dry","dead","forest","plains"}},
{rainfall=0.9,temperature=0.6,name="Wetland",biomeTypes={"dense","wet","lush","forest","swamp"}},
{rainfall=0.4,temperature=0.6,name="Woodland",biomeTypes={"dense","dry","forest"}},
{rainfall=0.4,temperature=0.5,name="Cold River",biomeTypes={"cold","coniferous","river","forest"}},
{rainfall=0.6,temperature=0.8,name="Temperate River",biomeTypes={"cold","river","forest"}},
{rainfall=0.4,temperature=0.5,name="Cold Ocean",biomeTypes={"cold","coniferous","ocean","forest","beach"}},
{rainfall=0.6,temperature=0.8,name="Temperate Ocean",biomeTypes={"cold","ocean","forest","beach"}},
{rainfall=0.1,temperature=0.0,name="Snow Forest",biomeTypes={"cold","coniferous","forest","snowy"}},
{rainfall=0.4,temperature=0.5,name="Cold Forest",biomeTypes={"cold","dense","coniferous","forest","hills"}},
{rainfall=0.6,temperature=0.7,name="Redwood",biomeTypes={"cold","coniferous","forest"}},
{rainfall=0.4,temperature=0.5,name="Cold Forest",biomeTypes={"cold","dense","coniferous","forest","hills"}},
{rainfall=0.5,temperature=0.5,name="Twilight Forest",biomeTypes={"forest"}},
{rainfall=0.8,temperature=0.7,name="Dense Twilight Forest",biomeTypes={"dense","forest"}},
{rainfall=0.7,temperature=0.4,name="Twilight Highlands",biomeTypes={"coniferous","forest","mountain"}},
{rainfall=0.8,temperature=0.8,name="Mushroom Forest",biomeTypes={"mushroom","forest"}},
{rainfall=0.9,temperature=0.125,name="Snowy Forest",biomeTypes={"cold","coniferous","forest","snowy"}},
{rainfall=0.0,temperature=0.9,name="Oak Savanna",biomeTypes={"sparse","forest"}},
{rainfall=1.0,temperature=0.5,name="Firefly Forest",biomeTypes={"lush","forest"}},
{rainfall=1.0,temperature=0.8,name="Deep Mushroom Forest",biomeTypes={"mushroom","forest"}},
{rainfall=0.8,temperature=0.7,name="Dark Forest",biomeTypes={"dense","spooky","forest"}},
{rainfall=0.5,temperature=0.5,name="Enchanted Forest",biomeTypes={"magical","forest"}},
{rainfall=0.8,temperature=0.7,name="Dark Forest Center",biomeTypes={"dense","spooky","magical","forest"}},
{rainfall=0.8,temperature=0.7,name="Flower Forest",biomeTypes={"forest","hills"}},
{rainfall=0.8,temperature=0.25,name="Mega Spruce Taiga",biomeTypes={"dense","forest"}},
{rainfall=0.0,temperature=2.0,name="Mesa Plateau F M",biomeTypes={"hot","dry","forest","sandy"}},
{rainfall=0.7,temperature=0.5,name="Toxic Everglades",biomeTypes={"dense","dead","forest","hills"}},
{rainfall=0.3,temperature=0.2,name="Extreme Hills",biomeTypes={"mountain","hills"}},
{rainfall=0.8,temperature=0.25,name="TaigaHills",biomeTypes={"cold","coniferous","forest","hills"}},
{rainfall=0.0,temperature=2.0,name="DesertHills",biomeTypes={"hot","dry","hills","sandy"}},
{rainfall=0.9,temperature=0.95,name="JungleHills",biomeTypes={"hot","dense","wet","jungle","hills"}},
{rainfall=0.8,temperature=0.7,name="ForestHills",biomeTypes={"forest","hills"}},
{rainfall=0.6,temperature=0.6,name="Birch Forest Hills",biomeTypes={"forest","hills"}},
{rainfall=0.4,temperature=-0.5,name="Cold Taiga Hills",biomeTypes={"cold","coniferous","forest","hills","snowy"}},
{rainfall=0.8,temperature=0.3,name="Mega Taiga Hills",biomeTypes={"cold","coniferous","forest","hills"}},
{rainfall=0.3,temperature=1.0,name="Canyon",biomeTypes={"hot","sparse","dry","mountain","hills","sandy"}},
{rainfall=0.3,temperature=1.0,name="Canyon Ravine",biomeTypes={"hot","dry","hills","sandy"}},
{rainfall=0.5,temperature=0.5,name="Coniferous Forest",biomeTypes={"dense","coniferous","forest","hills"}},
{rainfall=0.5,temperature=0.0,name="Snowy Coniferous Forest",biomeTypes={"cold","dense","coniferous","forest","hills","snowy"}},
{rainfall=0.2,temperature=0.0,name="Glacier",biomeTypes={"cold","dead","hills","snowy"}},
{rainfall=0.7,temperature=0.6,name="Grassland",biomeTypes={"sparse","lush","plains","hills","swamp"}},
{rainfall=0.8,temperature=0.5,name="Highland",biomeTypes={"sparse","mountain","hills"}},
{rainfall=1.0,temperature=0.5,name="Moor",biomeTypes={"sparse","wet","hills","swamp"}},
{rainfall=1.0,temperature=1.0,name="Rainforest",biomeTypes={"dense","wet","jungle","lush","forest","hills"}},
{rainfall=1.2,temperature=0.8,name="Temperate Rainforest",biomeTypes={"wet","coniferous","lush","forest","hills"}},
{rainfall=0.4,temperature=0.5,name="Cold Forest",biomeTypes={"cold","dense","coniferous","forest","hills"}},
{rainfall=0.2,temperature=0.3,name="Thornlands",biomeTypes={"dry","dead","hills","wasteland"}},
{rainfall=0.3,temperature=0.2,name="Extreme Hills M",biomeTypes={"hills"}},
{rainfall=0.8,temperature=0.7,name="Flower Forest",biomeTypes={"forest","hills"}},
{rainfall=0.8,temperature=0.25,name="Taiga M",biomeTypes={"hills"}},
{rainfall=0.5,temperature=0.0,name="Ice Plains Spikes",biomeTypes={"cold","hills","snowy"}},
{rainfall=0.9,temperature=0.95,name="Jungle M",biomeTypes={"hot","wet","hills"}},
{rainfall=0.8,temperature=0.95,name="JungleEdge M",biomeTypes={"hot","hills"}},
{rainfall=0.6,temperature=0.6,name="Birch Forest M",biomeTypes={"hills"}},
{rainfall=0.6,temperature=0.6,name="Birch Forest Hills M",biomeTypes={"hills"}},
{rainfall=0.8,temperature=0.7,name="Roofed Forest M",biomeTypes={"hills"}},
{rainfall=0.4,temperature=-0.5,name="Cold Taiga M",biomeTypes={"cold","hills","snowy"}},
{rainfall=0.3,temperature=0.2,name="Extreme Hills+ M",biomeTypes={"hills"}},
{rainfall=0.0,temperature=1.1,name="Savanna M",biomeTypes={"hot","sparse","dry","savanna","hills"}},
{rainfall=0.0,temperature=1.0,name="Savanna Plateau M",biomeTypes={"hot","sparse","dry","savanna","hills"}},
{rainfall=0.7,temperature=0.5,name="Toxic Everglades",biomeTypes={"dense","dead","forest","hills"}},
{rainfall=0.0,temperature=2.0,name="Mesa",biomeTypes={"mesa","sandy"}},
{rainfall=0.0,temperature=2.0,name="Mesa Plateau F",biomeTypes={"sparse","mesa","sandy"}},
{rainfall=0.0,temperature=2.0,name="Mesa Plateau",biomeTypes={"mesa","sandy"}},
{rainfall=0.2,temperature=0.3,name="Highlands Center",biomeTypes={"dry","dead","mesa","wasteland"}},
{rainfall=0.3,temperature=0.2,name="Extreme Hills",biomeTypes={"mountain","hills"}},
{rainfall=0.5,temperature=0.0,name="Ice Mountains",biomeTypes={"cold","mountain","snowy"}},
{rainfall=0.3,temperature=0.2,name="Extreme Hills Edge",biomeTypes={"mountain"}},
{rainfall=0.3,temperature=0.2,name="Extreme Hills+",biomeTypes={"sparse","forest","mountain"}},
{rainfall=0.5,temperature=0.0,name="Alps",biomeTypes={"cold","mountain","snowy"}},
{rainfall=0.5,temperature=0.0,name="Alps Forest",biomeTypes={"cold","forest","mountain","snowy"}},
{rainfall=0.3,temperature=1.0,name="Canyon",biomeTypes={"hot","sparse","dry","mountain","hills","sandy"}},
{rainfall=0.0,temperature=1.0,name="Crag",biomeTypes={"dry","spooky","dead","mountain","wasteland"}},
{rainfall=0.8,temperature=0.5,name="Highland",biomeTypes={"sparse","mountain","hills"}},
{rainfall=0.9,temperature=0.8,name="Jade Cliffs",biomeTypes={"dense","forest","mountain"}},
{rainfall=0.1,temperature=0.5,name="Mountain",biomeTypes={"dry","forest","mountain"}},
{rainfall=0.5,temperature=0.5,name="Sacred Springs",biomeTypes={"dense","wet","lush","magical","forest","mountain"}},
{rainfall=0.05,temperature=2.0,name="Volcano",biomeTypes={"hot","dry","mountain","wasteland"}},
{rainfall=0.7,temperature=0.4,name="Twilight Highlands",biomeTypes={"coniferous","forest","mountain"}},
{rainfall=0.4,temperature=0.8,name="Plains",biomeTypes={"plains"}},
{rainfall=0.0,temperature=1.2,name="Savanna",biomeTypes={"hot","sparse","savanna","plains"}},
{rainfall=0.0,temperature=1.0,name="Savanna Plateau",biomeTypes={"hot","sparse","savanna","plains"}},
{rainfall=0.1,temperature=1.2,name="Brushland",biomeTypes={"hot","dry","savanna","plains"}},
{rainfall=0.6,temperature=0.8,name="Chaparral",biomeTypes={"sparse","plains"}},
{rainfall=0.7,temperature=0.6,name="Flower Field",biomeTypes={"lush","plains"}},
{rainfall=0.8,temperature=0.7,name="Garden",biomeTypes={"lush","magical","plains"}},
{rainfall=0.7,temperature=0.6,name="Grassland",biomeTypes={"sparse","lush","plains","hills","swamp"}},
{rainfall=0.8,temperature=0.7,name="Grove",biomeTypes={"dense","lush","forest","plains"}},
{rainfall=0.2,temperature=0.8,name="Heathland",biomeTypes={"dry","savanna","plains"}},
{rainfall=0.7,temperature=0.6,name="Lavender Fields",biomeTypes={"sparse","lush","plains"}},
{rainfall=0.7,temperature=0.7,name="Meadow",biomeTypes={"lush","forest","plains"}},
{rainfall=0.7,temperature=0.7,name="Meadow Forest",biomeTypes={"lush","forest","plains"}},
{rainfall=0.7,temperature=0.7,name="Orchard",biomeTypes={"sparse","lush","forest","plains"}},
{rainfall=0.05,temperature=1.3,name="Outback",biomeTypes={"hot","dry","savanna","plains","sandy"}},
{rainfall=0.3,temperature=0.8,name="Prairie",biomeTypes={"sparse","dry","plains"}},
{rainfall=0.0,temperature=1.2,name="Scrubland",biomeTypes={"hot","sparse","dry","savanna","plains"}},
{rainfall=0.05,temperature=0.6,name="Shrubland",biomeTypes={"sparse","dry","plains"}},
{rainfall=0.05,temperature=0.7,name="Steppe",biomeTypes={"hot","sparse","dry","savanna","dead","plains","sandy"}},
{rainfall=0.2,temperature=0.6,name="Thicket",biomeTypes={"dense","dry","dead","forest","plains"}},
{rainfall=0.1,temperature=0.9,name="Hot Plains",biomeTypes={"hot","sparse","savanna","plains"}},
{rainfall=0.2,temperature=0.8,name="Hot Forest",biomeTypes={"hot","sparse","savanna","plains"}},
{rainfall=0.4,temperature=0.6,name="Plains (RWG)",biomeTypes={"plains"}},
{rainfall=0.4,temperature=0.8,name="Twilight Clearing",biomeTypes={"sparse","plains"}},
{rainfall=0.0,temperature=1.0,name="Dry River",biomeTypes={"hot","dry","plains","sandy"}},
{rainfall=1.0,temperature=0.9,name="Eucalyptus Forest",biomeTypes={"hot","wet","plains"}},
{rainfall=0.9,temperature=0.5,name="Land of Lakes",biomeTypes={"wet","plains"}},
{rainfall=0.8,temperature=0.7,name="Lush River",biomeTypes={"river","plains"}},
{rainfall=0.8,temperature=0.7,name="Origin Valley",biomeTypes={"plains"}},
{rainfall=0.0,temperature=2.0,name="Polar Chasm",biomeTypes={"hot","dry","savanna","plains"}},
{rainfall=0.8,temperature=0.5,name="Seasonal Forest Clearing",biomeTypes={"plains"}},
{rainfall=0.0,temperature=2.0,name="Spectral Garden",biomeTypes={"hot","dry","savanna","plains"}},
{rainfall=0.2,temperature=1.0,name="Xeric Shrubland",biomeTypes={"hot","plains","sandy"}},
{rainfall=0.7,temperature=0.7,name="Dense Forest",biomeTypes={"plains"}},
{rainfall=0.4,temperature=0.8,name="Sunflower Plains",biomeTypes={"plains"}},
{rainfall=0.0,temperature=2.0,name="Desert M",biomeTypes={"hot","dry","plains","sandy"}},
{rainfall=0.5,temperature=-4.5967,name="Storage Cell",biomeTypes={"cold","plains"}},
{rainfall=0.0,temperature=0.5,name="space",biomeTypes={"dry","plains"}},
{rainfall=0.0,temperature=2.0,name="Mesa (Bryce)",biomeTypes={"hot","dry","plains","sandy"}},
{rainfall=0.0,temperature=2.0,name="Mesa Plateau M",biomeTypes={"hot","dry","plains","sandy"}},
{rainfall=0.9,temperature=0.9,name="Oasis",biomeTypes={"hot","wet","plains"}},
{rainfall=0.6,temperature=0.8,name="Temperate Forest",biomeTypes={"plains"}},
{rainfall=0.0,temperature=2.0,name="Desert",biomeTypes={"hot","dry","sandy"}},
{rainfall=0.0,temperature=2.0,name="DesertHills",biomeTypes={"hot","dry","hills","sandy"}},
{rainfall=0.0,temperature=2.0,name="Mesa",biomeTypes={"mesa","sandy"}},
{rainfall=0.0,temperature=2.0,name="Mesa Plateau F",biomeTypes={"sparse","mesa","sandy"}},
{rainfall=0.0,temperature=2.0,name="Mesa Plateau",biomeTypes={"mesa","sandy"}},
{rainfall=0.0,temperature=2.0,name="Desert Oil Field",biomeTypes={"sandy"}},
{rainfall=0.0,temperature=0.5,name="marsFlat",biomeTypes={"cold","dry","dead","sandy"}},
{rainfall=0.3,temperature=1.0,name="Canyon",biomeTypes={"hot","sparse","dry","mountain","hills","sandy"}},
{rainfall=0.3,temperature=1.0,name="Canyon Ravine",biomeTypes={"hot","dry","hills","sandy"}},
{rainfall=0.0,temperature=2.0,name="Corrupted Sands",biomeTypes={"spooky","nether","sandy"}},
{rainfall=0.5,temperature=1.1,name="Lush Desert",biomeTypes={"hot","dry","savanna","lush","sandy"}},
{rainfall=0.9,temperature=0.9,name="Oasis",biomeTypes={"hot","wet","plains"}},
{rainfall=0.05,temperature=1.3,name="Outback",biomeTypes={"hot","dry","savanna","plains","sandy"}},
{rainfall=0.05,temperature=0.7,name="Steppe",biomeTypes={"hot","sparse","dry","savanna","dead","plains","sandy"}},
{rainfall=0.2,temperature=0.8,name="Hot River",biomeTypes={"hot","dry","river","sandy"}},
{rainfall=0.2,temperature=0.8,name="Hot Ocean",biomeTypes={"hot","dry","ocean","sandy","beach","ScummyBee"}},
{rainfall=0.0,temperature=1.0,name="Hot Desert",biomeTypes={"hot","dry","sandy"}},
{rainfall=0.0,temperature=1.0,name="Dry River",biomeTypes={"hot","dry","plains","sandy"}},
{rainfall=0.2,temperature=1.0,name="Xeric Shrubland",biomeTypes={"hot","plains","sandy"}},
{rainfall=0.0,temperature=2.0,name="Desert M",biomeTypes={"hot","dry","plains","sandy"}},
{rainfall=0.0,temperature=2.0,name="Mesa (Bryce)",biomeTypes={"hot","dry","plains","sandy"}},
{rainfall=0.0,temperature=2.0,name="Mesa Plateau F M",biomeTypes={"hot","dry","forest","sandy"}},
{rainfall=0.0,temperature=2.0,name="Mesa Plateau M",biomeTypes={"hot","dry","plains","sandy"}},
{rainfall=0.5,temperature=0.0,name="FrozenOcean",biomeTypes={"cold","ocean","snowy"}},
{rainfall=0.5,temperature=0.0,name="FrozenRiver",biomeTypes={"cold","river","snowy"}},
{rainfall=0.5,temperature=0.0,name="Ice Plains",biomeTypes={"cold","snowy","wasteland"}},
{rainfall=0.5,temperature=0.0,name="Ice Mountains",biomeTypes={"cold","mountain","snowy"}},
{rainfall=0.3,temperature=0.05,name="Cold Beach",biomeTypes={"cold","snowy","beach"}},
{rainfall=0.4,temperature=-0.5,name="Cold Taiga",biomeTypes={"cold","coniferous","forest","snowy"}},
{rainfall=0.4,temperature=-0.5,name="Cold Taiga Hills",biomeTypes={"cold","coniferous","forest","hills","snowy"}},
{rainfall=0.5,temperature=0.0,name="Alps",biomeTypes={"cold","mountain","snowy"}},
{rainfall=0.5,temperature=0.0,name="Alps Forest",biomeTypes={"cold","forest","mountain","snowy"}},
{rainfall=0.5,temperature=0.05,name="Arctic",biomeTypes={"cold","dead","snowy","wasteland"}},
{rainfall=0.5,temperature=0.0,name="Snowy Coniferous Forest",biomeTypes={"cold","dense","coniferous","forest","hills","snowy"}},
{rainfall=0.5,temperature=0.0,name="Frost Forest",biomeTypes={"cold","sparse","forest","snowy"}},
{rainfall=0.2,temperature=0.0,name="Glacier",biomeTypes={"cold","dead","hills","snowy"}},
{rainfall=0.1,temperature=0.0,name="Ice River",biomeTypes={"cold","river","snowy"}},
{rainfall=0.1,temperature=0.0,name="Ice Ocean",biomeTypes={"cold","ocean","snowy","beach"}},
{rainfall=0.1,temperature=0.0,name="Snow Desert",biomeTypes={"cold","snowy","wasteland"}},
{rainfall=0.1,temperature=0.0,name="Snow Forest",biomeTypes={"cold","coniferous","forest","snowy"}},
{rainfall=0.9,temperature=0.125,name="Snowy Forest",biomeTypes={"cold","coniferous","forest","snowy"}},
{rainfall=0.1,temperature=0.0,name="Twilight Glacier",biomeTypes={"cold","snowy","wasteland"}},
{rainfall=0.5,temperature=0.0,name="Ice Plains Spikes",biomeTypes={"cold","hills","snowy"}},
{rainfall=0.4,temperature=-0.5,name="Cold Taiga M",biomeTypes={"cold","hills","snowy"}},
{rainfall=0.9,temperature=0.8,name="Swampland",biomeTypes={"wet","swamp"}},
{rainfall=0.9,temperature=0.8,name="Bayou",biomeTypes={"wet","lush","ocean","river","swamp","ScummyBee"}},
{rainfall=0.9,temperature=0.5,name="Bog",biomeTypes={"wet","dead","forest","swamp"}},
{rainfall=0.9,temperature=0.7,name="Dead Swamp",biomeTypes={"sparse","spooky","dead","swamp"}},
{rainfall=0.4,temperature=0.4,name="Fen",biomeTypes={"wet","dead","forest","swamp"}},
{rainfall=1.0,temperature=0.9,name="Fungi Forest",biomeTypes={"wet","lush","mushroom","magical","forest","swamp"}},
{rainfall=0.7,temperature=0.6,name="Grassland",biomeTypes={"sparse","lush","plains","hills","swamp"}},
{rainfall=1.0,temperature=0.7,name="Lush Swamp",biomeTypes={"wet","lush","ocean","river","swamp","ScummyBee"}},
{rainfall=0.9,temperature=0.5,name="Marsh",biomeTypes={"sparse","wet","lush","ocean","river","swamp","ScummyBee"}},
{rainfall=1.0,temperature=0.5,name="Moor",biomeTypes={"sparse","wet","hills","swamp"}},
{rainfall=0.9,temperature=0.5,name="Ominous Woods",biomeTypes={"spooky","dead","magical","forest","swamp"}},
{rainfall=0.9,temperature=0.8,name="Quagmire",biomeTypes={"wet","spooky","dead","swamp","wasteland"}},
{rainfall=0.9,temperature=0.5,name="Silkglades",biomeTypes={"spooky","dead","forest","swamp"}},
{rainfall=0.9,temperature=0.8,name="Sludgepit",biomeTypes={"wet","spooky","dead","forest","swamp","wasteland"}},
{rainfall=0.9,temperature=0.6,name="Wetland",biomeTypes={"dense","wet","lush","forest","swamp"}},
{rainfall=0.9,temperature=0.8,name="Twilight Swamp",biomeTypes={"wet","swamp"}},
{rainfall=0.4,temperature=1.0,name="Fire Swamp",biomeTypes={"hot","swamp","wasteland"}},
{rainfall=0.9,temperature=0.5,name="Land of Lakes Marsh",biomeTypes={"wet","swamp"}},
{rainfall=0.9,temperature=0.8,name="Swampland M",biomeTypes={"wet","swamp"}},
{rainfall=0.5,temperature=0.0,name="Ice Plains",biomeTypes={"cold","snowy","wasteland"}},
{rainfall=0.5,temperature=0.5,name="Tainted Land",biomeTypes={"magical","wasteland"}},
{rainfall=0.5,temperature=0.05,name="Arctic",biomeTypes={"cold","dead","snowy","wasteland"}},
{rainfall=0.0,temperature=2.0,name="Boneyard",biomeTypes={"spooky","nether","wasteland"}},
{rainfall=0.0,temperature=1.0,name="Crag",biomeTypes={"dry","spooky","dead","mountain","wasteland"}},
{rainfall=0.9,temperature=0.8,name="Quagmire",biomeTypes={"wet","spooky","dead","swamp","wasteland"}},
{rainfall=0.9,temperature=0.8,name="Sludgepit",biomeTypes={"wet","spooky","dead","forest","swamp","wasteland"}},
{rainfall=0.5,temperature=0.2,name="Tundra",biomeTypes={"cold","sparse","dry","dead","wasteland"}},
{rainfall=0.05,temperature=2.0,name="Volcano",biomeTypes={"hot","dry","mountain","wasteland"}},
{rainfall=0.05,temperature=1.0,name="Wasteland",biomeTypes={"sparse","spooky","dead","wasteland"}},
{rainfall=0.1,temperature=0.0,name="Snow Desert",biomeTypes={"cold","snowy","wasteland"}},
{rainfall=0.2,temperature=0.2,name="Cold Plains",biomeTypes={"cold","wasteland"}},
{rainfall=0.1,temperature=0.0,name="Twilight Glacier",biomeTypes={"cold","snowy","wasteland"}},
{rainfall=0.4,temperature=1.0,name="Fire Swamp",biomeTypes={"hot","swamp","wasteland"}},
{rainfall=0.2,temperature=0.3,name="Highlands Center",biomeTypes={"dry","dead","mesa","wasteland"}},
{rainfall=0.2,temperature=0.3,name="Thornlands",biomeTypes={"dry","dead","hills","wasteland"}},
{rainfall=0.5,temperature=0.5,name="River",biomeTypes={"river"}},
{rainfall=0.5,temperature=0.0,name="FrozenRiver",biomeTypes={"cold","river","snowy"}},
{rainfall=0.5,temperature=0.5,name="Ocean Oil Field",biomeTypes={"ocean","river"}},
{rainfall=0.9,temperature=0.8,name="Bayou",biomeTypes={"wet","lush","ocean","river","swamp","ScummyBee"}},
{rainfall=1.0,temperature=0.7,name="Lush Swamp",biomeTypes={"wet","lush","ocean","river","swamp","ScummyBee"}},
{rainfall=0.9,temperature=0.8,name="Mangrove",biomeTypes={"wet","lush","ocean","river","forest","ScummyBee"}},
{rainfall=0.9,temperature=0.5,name="Marsh",biomeTypes={"sparse","wet","lush","ocean","river","swamp","ScummyBee"}},
{rainfall=0.9,temperature=0.5,name="Coral Reef",biomeTypes={"ocean","river"}},
{rainfall=0.9,temperature=0.5,name="Kelp Forest",biomeTypes={"ocean","river","forest"}},
{rainfall=0.8,temperature=0.5,name="Shield",biomeTypes={"wet","coniferous","ocean","river","forest","ScummyBee"}},
{rainfall=1.0,temperature=1.2,name="Tropics",biomeTypes={"wet","jungle","lush","ocean","river","beach","ScummyBee"}},
{rainfall=0.1,temperature=0.0,name="Ice River",biomeTypes={"cold","river","snowy"}},
{rainfall=0.4,temperature=0.5,name="Cold River",biomeTypes={"cold","coniferous","river","forest"}},
{rainfall=0.6,temperature=0.8,name="Temperate River",biomeTypes={"cold","river","forest"}},
{rainfall=0.2,temperature=0.8,name="Hot River",biomeTypes={"hot","dry","river","sandy"}},
{rainfall=0.9,temperature=0.9,name="Wet River",biomeTypes={"hot","wet","jungle","river"}},
{rainfall=0.9,temperature=0.9,name="River Oasis",biomeTypes={"hot","wet","jungle","river"}},
{rainfall=1.0,temperature=0.5,name="Twilight Stream",biomeTypes={"river"}},
{rainfall=0.8,temperature=0.7,name="Lush River",biomeTypes={"river","plains"}},
{rainfall=0.5,temperature=0.5,name="Ocean",biomeTypes={"ocean"}},
{rainfall=0.5,temperature=0.0,name="FrozenOcean",biomeTypes={"cold","ocean","snowy"}},
{rainfall=0.5,temperature=0.5,name="Deep Ocean",biomeTypes={"ocean"}},
{rainfall=0.5,temperature=0.5,name="Ocean Oil Field",biomeTypes={"ocean","river"}},
{rainfall=0.9,temperature=0.8,name="Bayou",biomeTypes={"wet","lush","ocean","river","swamp","ScummyBee"}},
{rainfall=1.0,temperature=0.7,name="Lush Swamp",biomeTypes={"wet","lush","ocean","river","swamp","ScummyBee"}},
{rainfall=0.9,temperature=0.8,name="Mangrove",biomeTypes={"wet","lush","ocean","river","forest","ScummyBee"}},
{rainfall=0.9,temperature=0.5,name="Marsh",biomeTypes={"sparse","wet","lush","ocean","river","swamp","ScummyBee"}},
{rainfall=0.9,temperature=0.5,name="Coral Reef",biomeTypes={"ocean","river"}},
{rainfall=0.9,temperature=0.5,name="Kelp Forest",biomeTypes={"ocean","river","forest"}},
{rainfall=0.8,temperature=0.5,name="Shield",biomeTypes={"wet","coniferous","ocean","river","forest","ScummyBee"}},
{rainfall=1.0,temperature=1.2,name="Tropics",biomeTypes={"wet","jungle","lush","ocean","river","beach","ScummyBee"}},
{rainfall=0.1,temperature=0.0,name="Ice Ocean",biomeTypes={"cold","ocean","snowy","beach"}},
{rainfall=0.4,temperature=0.5,name="Cold Ocean",biomeTypes={"cold","coniferous","ocean","forest","beach"}},
{rainfall=0.6,temperature=0.8,name="Temperate Ocean",biomeTypes={"cold","ocean","forest","beach"}},
{rainfall=0.2,temperature=0.8,name="Hot Ocean",biomeTypes={"hot","dry","ocean","sandy","beach","ScummyBee"}},
{rainfall=0.9,temperature=0.9,name="Wet Ocean",biomeTypes={"hot","wet","jungle","ocean","beach","ScummyBee"}},
{rainfall=0.9,temperature=0.9,name="Ocean Oasis",biomeTypes={"hot","wet","jungle","ocean","beach","ScummyBee"}},
{rainfall=1.0,temperature=0.66,name="Twilight Lake",biomeTypes={"ocean"}},
{rainfall=0.8,temperature=0.7,name="Roofed Forest",biomeTypes={"dense","spooky","forest"}},
{rainfall=0.5,temperature=0.5,name="Eerie",biomeTypes={"spooky","magical"}},
{rainfall=0.5,temperature=0.5,name="Eldritch",biomeTypes={"spooky","end","magical"}},
{rainfall=0.0,temperature=0.5,name="asteroids",biomeTypes={"cold","dry","spooky","dead"}},
{rainfall=0.0,temperature=2.0,name="Boneyard",biomeTypes={"spooky","nether","wasteland"}},
{rainfall=0.0,temperature=2.0,name="Corrupted Sands",biomeTypes={"spooky","nether","sandy"}},
{rainfall=0.0,temperature=1.0,name="Crag",biomeTypes={"dry","spooky","dead","mountain","wasteland"}},
{rainfall=0.3,temperature=0.4,name="Dead Forest",biomeTypes={"sparse","spooky","dead","forest"}},
{rainfall=0.9,temperature=0.7,name="Dead Swamp",biomeTypes={"sparse","spooky","dead","swamp"}},
{rainfall=0.9,temperature=0.5,name="Ominous Woods",biomeTypes={"spooky","dead","magical","forest","swamp"}},
{rainfall=0.0,temperature=2.0,name="Phantasmagoric Inferno",biomeTypes={"spooky","nether"}},
{rainfall=0.9,temperature=0.8,name="Quagmire",biomeTypes={"wet","spooky","dead","swamp","wasteland"}},
{rainfall=0.9,temperature=0.5,name="Silkglades",biomeTypes={"spooky","dead","forest","swamp"}},
{rainfall=0.9,temperature=0.8,name="Sludgepit",biomeTypes={"wet","spooky","dead","forest","swamp","wasteland"}},
{rainfall=0.0,temperature=2.0,name="Undergarden",biomeTypes={"jungle","spooky","nether"}},
{rainfall=0.0,temperature=2.0,name="Visceral Heap",biomeTypes={"spooky","nether"}},
{rainfall=0.05,temperature=1.0,name="Wasteland",biomeTypes={"sparse","spooky","dead","wasteland"}},
{rainfall=0.8,temperature=0.7,name="Dark Forest",biomeTypes={"dense","spooky","forest"}},
{rainfall=0.8,temperature=0.7,name="Dark Forest Center",biomeTypes={"dense","spooky","magical","forest"}},
{rainfall=0.0,temperature=0.5,name="Space",biomeTypes={"cold","dry","spooky","dead"}},
{rainfall=0.0,temperature=1.16,name="BarnardaCShores",biomeTypes={"cold","dry","spooky","dead"}},
{rainfall=0.0,temperature=1.16,name="BarnardaCHills",biomeTypes={"cold","dry","spooky","dead"}},
{rainfall=0.0,temperature=1.16,name="BarnardaCLowPlains",biomeTypes={"cold","dry","spooky","dead"}},
{rainfall=0.0,temperature=1.16,name="BarnardaCFlowers",biomeTypes={"cold","dry","spooky","dead"}},
{rainfall=0.0,temperature=1.16,name="BarnardaCOceans",biomeTypes={"cold","dry","spooky","dead"}},
{rainfall=0.0,temperature=0.5,name="Kuiper Belt",biomeTypes={"cold","dry","spooky","dead"}},
{rainfall=0.0,temperature=0.5,name="Pluto",biomeTypes={"cold","dry","spooky","dead"}},
{rainfall=0.0,temperature=0.5,name="Pluto2",biomeTypes={"cold","dry","spooky","dead"}},
{rainfall=0.0,temperature=0.5,name="Pluto3",biomeTypes={"cold","dry","spooky","dead"}},
{rainfall=0.0,temperature=0.5,name="Pluto4",biomeTypes={"cold","dry","spooky","dead"}},
{rainfall=0.0,temperature=1.0,name="Venus",biomeTypes={"cold","dry","spooky","dead"}},
{rainfall=0.0,temperature=0.5,name="Io",biomeTypes={"cold","dry","spooky","dead"}},
{rainfall=0.0,temperature=0.5,name="IoAsh",biomeTypes={"cold","dry","spooky","dead"}},
{rainfall=0.0,temperature=0.5,name="Titan",biomeTypes={"cold","dry","spooky","dead"}},
{rainfall=0.5,temperature=0.5,name="Tainted Land",biomeTypes={"magical","wasteland"}},
{rainfall=0.5,temperature=0.5,name="Eerie",biomeTypes={"spooky","magical"}},
{rainfall=0.5,temperature=0.5,name="Eldritch",biomeTypes={"spooky","end","magical"}},
{rainfall=0.6,temperature=0.7,name="Magical Forest",biomeTypes={"magical","forest"}},
{rainfall=0.8,temperature=0.6,name="Cherry Blossom Grove",biomeTypes={"lush","magical","forest"}},
{rainfall=1.0,temperature=0.9,name="Fungi Forest",biomeTypes={"wet","lush","mushroom","magical","forest","swamp"}},
{rainfall=0.8,temperature=0.7,name="Garden",biomeTypes={"lush","magical","plains"}},
{rainfall=1.0,temperature=0.7,name="Mystic Grove",biomeTypes={"wet","lush","magical","forest"}},
{rainfall=0.9,temperature=0.5,name="Ominous Woods",biomeTypes={"spooky","dead","magical","forest","swamp"}},
{rainfall=0.5,temperature=0.5,name="Sacred Springs",biomeTypes={"dense","wet","lush","magical","forest","mountain"}},
{rainfall=0.5,temperature=0.5,name="Enchanted Forest",biomeTypes={"magical","forest"}},
{rainfall=0.8,temperature=0.7,name="Dark Forest Center",biomeTypes={"dense","spooky","magical","forest"}}}